nginx-proxy:
  image: jwilder/nginx-proxy
  volumes:
    - /etc/nginx/conf.d
    - /etc/nginx/vhost.d
    - /usr/share/nginx/html
    - /storage/nginx-proxy/certs:/etc/nginx/certs:ro
    - /var/run/docker.sock:/tmp/docker.sock:ro
  restart: always
  ports:
    - 80:80
    - 443:443
  environment:
    - DEFAULT_HOST=plex.three-five.bshaw.io
letsencrypt:
  # image:  jrcs/letsencrypt-nginx-proxy-companion
  image: alastaircoote/docker-letsencrypt-nginx-proxy-companion
  volumes:
    - /storage/nginx-proxy/certs:/etc/nginx/certs:rw
    - /var/run/docker.sock:/var/run/docker.sock:ro
  volumes_from:
    - nginx-proxy
  restart: always
